name: Bug Report
description: Broken or unintended behavior with one of our libraries.
labels: [bug-unconfirmed, question]
body:
- type: markdown
  attributes:
    value: |
      ## Before Submitting your Issue
      Please check to see if your question is answered in the FAQ for the library you are using:
      - [@azure/msal-browser](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md)
      - [@azure/msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md)
      - [@azure/msal-angular](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md)
      - [@azure/msal-react](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md)
      - [@azure/msal or msal](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/FAQ.md)
      
      If you have questions about timelines, please see our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md). Issues pertaining to timelines may be closed without comment.

- type: markdown
  attributes:
    value: |
      ## Issue Details
    
- type: dropdown
  attributes:
    label: Core Library
    options: 
      - "MSAL.js v2 (@azure/msal-browser)"
      - "MSAL.js v1 (@azure/msal or msal)"
      - "MSAL Node (@azure/msal-node)"
      - "Passport Azure AD (passport-azure-ad)"
      - "ADAL Node (adal-node)"
      - "ADAL.js (adal.js)"
  validations:
    required: true
    
- type: input
  attributes:
    label: Core Library Version
    description: "Please enter the latest version this issue can be reproduced in."
    placeholder: "2.14.1"
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Wrapper Library
    options:
      - "MSAL Angular (@azure/msal-angular)"
      - "MSAL React (@azure/msal-react)"
      - "MSAL Node Extensions (@azure/msal-node-extensions)"
      - "ADAL Angular (adal-angular)"
      - "Not Applicable"
  validations:
    required: true
    
- type: input
  attributes:
    label: Wrapper Library Version
    description: "Please enter the latest version this issue can be reproduced in. If you are not using a wrapper library please enter 'None'"
    placeholder: "2.0.0-beta.0"
  validations:
    required: true

- type: dropdown
  attributes:
    label: Public or Confidential Client?
    description: Are you using PublicClientApplication or ConfidentialClientApplication? (Issues regarding msal-browser, msal-react and msal-angular are always "Public")
    multiple: true
    options: 
      - "Public"
      - "Confidential"
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Description
    description: "Please briefly describe your issue."
  validations: 
    required: true
    
- type: textarea
  attributes:
    label: Error Message
    description: "Please provide any error message you are receiving and a stack trace."

- type: textarea
  attributes:
    label: Msal Logs
    description: "Please provide verbose level log messages from msal."
    
- type: textarea
  attributes:
    label: MSAL Configuration
    description: "Please provide your MSAL configuration."
    render: javascript
    placeholder: |
      {
        auth: {
          clientId: "clientId",
          authority: "https://login.microsoftonline.com/common/"
        },
        cache: {
          cacheLocation: "sessionStorage"
          storeAuthStateInCookie: false
        }
      }
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Relevant Code Snippets
    description: "Please provide relevant code snippets that can be used to reproduce this issue."
    render: javascript
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Reproduction Steps
    description: "Please provide steps to reproduce or a link to a sample which demonstrates this behavior."
    placeholder: |
      1.
      2.
      3.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Expected Behavior
    description: "Please describe what you expect the behavior to be."
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Identity Provider
    options: 
      - Azure AD / MSA
      - Azure B2C Basic Policy
      - Azure B2C Custom Policy
      - ADFS
      - Other
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Browsers Affected (Select all that apply)
    multiple: true
    options: 
      - Chrome
      - Firefox
      - Edge
      - Safari
      - Internet Explorer
      - None (Server)
      - Other
  validations:
    required: true
    
- type: input
  attributes:
    label: Regression
    description: "If this behavior worked before, please enter the last working version(s)."
    placeholder: "@azure/msal-browser 2.0.0"
    
- type: dropdown
  attributes:
    label: Source
    description: "Are you an internal or external customer?"
    options: 
      - Internal (Microsoft)
      - External (Customer)
  validations: 
     required: true
    
- type: markdown
  attributes:
    value: "## Security Reporting"
- type: markdown
  attributes:
    value: |
      If you find a security issue with our libraries or services [please report it to the Microsoft Security Response Center (MSRC)](https://aka.ms/report-security-issue) with as much detail as possible. Your submission may be eligible for a bounty through the [Microsoft Bounty](http://aka.ms/bugbounty) program. Please do not post security issues to GitHub Issues or any other public site. We will contact you shortly upon receiving the information. We encourage you to get notifications of when security incidents occur by visiting [this page](https://www.microsoft.com/msrc/technical-security-notifications) and subscribing to Security Advisory Alerts.
