# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Will not trigger unless PR is ready for review.

name: msal-core E2E Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'lib/msal-core/**/*'
      - 'samples/msal-core-samples/VanillaJSTestApp/**/*'
      - '!**.md'
      - '.github/workflows/msal-core-e2e.yml'
  merge_group:
    types: [checks_requested]

concurrency:
  group: core-e2e-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-e2e:
    if: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && (github.actor != 'dependabot[bot]') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'merge_group')) && !github.event.pull_request.draft

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Restore node_modules for libs
      uses: actions/cache@v3
      id: lib-cache
      with:
        path: |
          node_modules
          lib/*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json', 'lib/*/package-lock.json') }}

    - name: Clean Install
      if: steps.lib-cache.outputs.cache-hit != 'true'
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Restore node_modules for sample
      uses: actions/cache@v3
      id: sample-cache
      with:
        path: samples/msal-core-samples/VanillaJSTestApp/node_modules
        key: ${{ runner.os }}-core-e2e-${{ hashFiles('samples/msal-core-samples/VanillaJSTestApp/package.json') }}

    - name: Install Sample
      if: steps.sample-cache.outputs.cache-hit != 'true'
      working-directory: samples/msal-core-samples/VanillaJSTestApp
      run: npm install

    - name: Build packages
      working-directory: samples/msal-core-samples/VanillaJSTestApp
      run: npm run build:package

    - name: E2E Tests
      working-directory: samples/msal-core-samples/VanillaJSTestApp
      timeout-minutes: 5
      env:
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      run: npm run test:e2e

    - name: Upload E2E Test Screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: e2e-test-screenshots
        path: samples/**/screenshots
